import { useState, useCallback, createElement } from 'react';
import { createRoot } from 'react-dom/client';
import { QRCodeCanvas } from 'qrcode.react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Pet } from '../types/pet';
import type { PlatformKey } from '../types/platform';
import { PLATFORMS } from '../types/platform';
import type { PlatformCaptions } from '../api/gemini';
import { assetPlatformUrl, videoPlatformUrl } from '../cloudinary/transformations';
import { getFilenameForPlatform } from '../utils/platformSpecs';
import { getProfileUrl } from '../utils/profileUrl';

const PLATFORM_LABELS: Record<string, string> = {
  instagram_feed: 'Instagram Feed',
  instagram_story: 'Instagram Story',
  twitter: 'Twitter',
  facebook: 'Facebook',
  youtube_thumb: 'YouTube Thumbnail',
};

function buildCaptionText(pet: Pet): string {
  const lines: string[] = [];
  lines.push(pet.caption || '(No caption generated yet)');
  lines.push('');
  lines.push('---');
  lines.push(`Shelter: ${pet.shelterName}`);
  if (pet.shelterLocation) lines.push(`Location: ${pet.shelterLocation}`);
  if (pet.shelterContact) lines.push(`Contact: ${pet.shelterContact}`);
  lines.push('');
  lines.push('Generated by PawPrint');
  return lines.join('\n');
}

function buildPlatformCaptionText(
  platformKey: string,
  caption: { caption: string; hashtags: string[] },
  pet: Pet,
): string {
  const lines: string[] = [];

  // Copy-paste-ready block at the top — paste directly into the platform
  lines.push(caption.caption);
  if (caption.hashtags.length > 0) {
    lines.push('');
    lines.push(caption.hashtags.map((h) => `#${h}`).join(' '));
  }

  // Metadata below a clear separator
  lines.push('');
  lines.push('');
  lines.push(`— ${PLATFORM_LABELS[platformKey] || platformKey} caption by PawPrint —`);
  lines.push(`Shelter: ${pet.shelterName}`);
  if (pet.shelterLocation) lines.push(`Location: ${pet.shelterLocation}`);
  if (pet.shelterContact) lines.push(`Contact: ${pet.shelterContact}`);
  return lines.join('\n');
}

/** Force jpg at max quality for images; keep actual video for video assets. */
function downloadUrl(publicId: string, platform: PlatformKey, resourceType = 'image'): string {
  if (resourceType === 'video') {
    return videoPlatformUrl(publicId, platform);
  }
  const url = assetPlatformUrl(publicId, platform, resourceType);
  return url.replace(/\/f_auto[^/]*/, '/f_jpg,q_95');
}

async function fetchImageBlob(url: string): Promise<Blob> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch image: ${res.status}`);
  return res.blob();
}

/** Render a QR code to an offscreen canvas and return as PNG blob. */
function generateQrBlob(url: string): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const container = document.createElement('div');
    container.style.position = 'fixed';
    container.style.left = '-9999px';
    document.body.appendChild(container);

    const root = createRoot(container);
    root.render(
      createElement(QRCodeCanvas, {
        value: url,
        size: 512,
        fgColor: '#002b60',
        bgColor: '#ffffff',
        level: 'M',
      }),
    );

    // Give React a tick to render
    requestAnimationFrame(() => {
      const canvas = container.querySelector('canvas');
      if (!canvas) {
        root.unmount();
        document.body.removeChild(container);
        reject(new Error('QR canvas not found'));
        return;
      }
      canvas.toBlob((blob) => {
        root.unmount();
        document.body.removeChild(container);
        if (blob) resolve(blob);
        else reject(new Error('Failed to export QR canvas'));
      }, 'image/png');
    });
  });
}

interface UseDownloadPackResult {
  downloadPlatform: (platform: PlatformKey) => Promise<void>;
  downloadAll: () => Promise<void>;
  progress: number;
  isGenerating: boolean;
  error: string | null;
  skippedCount: number;
}

export function useDownloadPack(pet: Pet | null, platformCaptions?: PlatformCaptions | null): UseDownloadPackResult {
  const [progress, setProgress] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [skippedCount, setSkippedCount] = useState(0);

  const downloadPlatform = useCallback(
    async (platform: PlatformKey) => {
      if (!pet || pet.publicIds.length === 0) return;
      setIsGenerating(true);
      setProgress(0);
      setError(null);
      setSkippedCount(0);

      try {
        const zip = new JSZip();
        const total = pet.publicIds.length;
        let skipped = 0;

        for (let i = 0; i < pet.publicIds.length; i++) {
          try {
            const rt = pet.resourceTypes?.[i] || 'image';
            const url = downloadUrl(pet.publicIds[i], platform, rt);
            const blob = await fetchImageBlob(url);
            const filename = getFilenameForPlatform(pet.name, platform, i + 1, rt);
            zip.file(filename, blob);
          } catch (err) {
            console.error(`Skipped asset ${i + 1}:`, err);
            skipped++;
          }
          setProgress(Math.round(((i + 1) / total) * 100));
        }

        setSkippedCount(skipped);

        if (skipped === total) {
          setError('Failed to download images. Please check your connection and try again.');
          return;
        }

        // Include platform-specific caption if available, fallback to general
        const pc = platformCaptions?.[platform];
        if (pc) {
          zip.file('caption.txt', buildPlatformCaptionText(platform, pc, pet));
        } else {
          zip.file('caption.txt', buildCaptionText(pet));
        }

        // Add QR code and profile link
        const profileUrl = getProfileUrl(pet.id);
        zip.file('profile-link.txt', profileUrl);
        try {
          const qrBlob = await generateQrBlob(profileUrl);
          zip.file('qr-code.png', qrBlob);
        } catch (err) {
          console.error('QR code generation skipped:', err);
        }

        const content = await zip.generateAsync({ type: 'blob' });
        const safeName = pet.name.replace(/[^a-zA-Z0-9]+/g, '_').replace(/_+$/, '');
        saveAs(content, `${safeName}_${platform}.zip`);
      } catch (err) {
        console.error('ZIP generation failed:', err);
        setError('Something went wrong generating the download. Please try again.');
      } finally {
        setIsGenerating(false);
        setProgress(0);
      }
    },
    [pet, platformCaptions],
  );

  const downloadAll = useCallback(async () => {
    if (!pet || pet.publicIds.length === 0) return;
    setIsGenerating(true);
    setProgress(0);
    setError(null);
    setSkippedCount(0);

    try {
      const zip = new JSZip();
      const total = pet.publicIds.length * PLATFORMS.length;
      let fetched = 0;
      let skipped = 0;

      for (const platform of PLATFORMS) {
        const folder = zip.folder(platform.label)!;
        for (let i = 0; i < pet.publicIds.length; i++) {
          try {
            const rt = pet.resourceTypes?.[i] || 'image';
            const url = downloadUrl(pet.publicIds[i], platform.key, rt);
            const blob = await fetchImageBlob(url);
            const filename = getFilenameForPlatform(pet.name, platform.key, i + 1, rt);
            folder.file(filename, blob);
          } catch (err) {
            console.error(`Skipped ${platform.label} asset ${i + 1}:`, err);
            skipped++;
          }
          fetched++;
          setProgress(Math.round((fetched / total) * 100));
        }

        // Add platform-specific caption to each folder (fallback to general)
        const pc = platformCaptions?.[platform.key];
        if (pc) {
          folder.file('caption.txt', buildPlatformCaptionText(platform.key, pc, pet));
        } else {
          folder.file('caption.txt', buildCaptionText(pet));
        }
      }

      setSkippedCount(skipped);

      if (skipped === total) {
        setError('Failed to download images. Please check your connection and try again.');
        return;
      }

      // General caption at root level
      zip.file('caption.txt', buildCaptionText(pet));

      // Add QR code and profile link
      const profileUrl = getProfileUrl(pet.id);
      zip.file('profile-link.txt', profileUrl);
      try {
        const qrBlob = await generateQrBlob(profileUrl);
        zip.file('qr-code.png', qrBlob);
      } catch (err) {
        console.error('QR code generation skipped:', err);
      }

      const content = await zip.generateAsync({ type: 'blob' });
      const safeName = pet.name.replace(/[^a-zA-Z0-9]+/g, '_').replace(/_+$/, '');
      saveAs(content, `${safeName}_all_platforms.zip`);
    } catch (err) {
      console.error('ZIP generation failed:', err);
      setError('Something went wrong generating the download. Please try again.');
    } finally {
      setIsGenerating(false);
      setProgress(0);
    }
  }, [pet, platformCaptions]);

  return { downloadPlatform, downloadAll, progress, isGenerating, error, skippedCount };
}
