import { useState, useCallback } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Pet } from '../types/pet';
import type { PlatformKey } from '../types/platform';
import { PLATFORMS } from '../types/platform';
import { platformUrl } from '../cloudinary/transformations';
import { getFilenameForPlatform } from '../utils/platformSpecs';

function buildCaptionText(pet: Pet): string {
  const lines: string[] = [];
  lines.push(pet.caption || '(No caption generated yet)');
  lines.push('');
  lines.push('---');
  lines.push(`Shelter: ${pet.shelterName}`);
  if (pet.shelterLocation) lines.push(`Location: ${pet.shelterLocation}`);
  if (pet.shelterContact) lines.push(`Contact: ${pet.shelterContact}`);
  lines.push('');
  lines.push('Generated by PawPrint');
  return lines.join('\n');
}

/** Force jpg format for consistent downloads instead of f_auto (which may return webp). */
function downloadUrl(publicId: string, platform: PlatformKey): string {
  const url = platformUrl(publicId, platform);
  return url.replace('/f_auto,', '/f_jpg,');
}

async function fetchImageBlob(url: string): Promise<Blob> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch image: ${res.status}`);
  return res.blob();
}

interface UseDownloadPackResult {
  downloadPlatform: (platform: PlatformKey) => Promise<void>;
  downloadAll: () => Promise<void>;
  progress: number;
  isGenerating: boolean;
}

export function useDownloadPack(pet: Pet | null): UseDownloadPackResult {
  const [progress, setProgress] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);

  const downloadPlatform = useCallback(
    async (platform: PlatformKey) => {
      if (!pet || pet.publicIds.length === 0) return;
      setIsGenerating(true);
      setProgress(0);

      try {
        const zip = new JSZip();
        const total = pet.publicIds.length;

        for (let i = 0; i < pet.publicIds.length; i++) {
          const url = downloadUrl(pet.publicIds[i], platform);
          const blob = await fetchImageBlob(url);
          const filename = getFilenameForPlatform(pet.name, platform, i + 1);
          zip.file(filename, blob);
          setProgress(Math.round(((i + 1) / total) * 100));
        }

        zip.file('caption.txt', buildCaptionText(pet));

        const content = await zip.generateAsync({ type: 'blob' });
        const safeName = pet.name.replace(/[^a-zA-Z0-9]+/g, '_').replace(/_+$/, '');
        saveAs(content, `${safeName}_${platform}.zip`);
      } finally {
        setIsGenerating(false);
        setProgress(0);
      }
    },
    [pet],
  );

  const downloadAll = useCallback(async () => {
    if (!pet || pet.publicIds.length === 0) return;
    setIsGenerating(true);
    setProgress(0);

    try {
      const zip = new JSZip();
      const total = pet.publicIds.length * PLATFORMS.length;
      let fetched = 0;

      for (const platform of PLATFORMS) {
        const folder = zip.folder(platform.label)!;
        for (let i = 0; i < pet.publicIds.length; i++) {
          const url = downloadUrl(pet.publicIds[i], platform.key);
          const blob = await fetchImageBlob(url);
          const filename = getFilenameForPlatform(pet.name, platform.key, i + 1);
          folder.file(filename, blob);
          fetched++;
          setProgress(Math.round((fetched / total) * 100));
        }
      }

      zip.file('caption.txt', buildCaptionText(pet));

      const content = await zip.generateAsync({ type: 'blob' });
      const safeName = pet.name.replace(/[^a-zA-Z0-9]+/g, '_').replace(/_+$/, '');
      saveAs(content, `${safeName}_all_platforms.zip`);
    } finally {
      setIsGenerating(false);
      setProgress(0);
    }
  }, [pet]);

  return { downloadPlatform, downloadAll, progress, isGenerating };
}
