import { useState, useCallback, useEffect, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { usePet } from '../hooks/usePet';
import { useDownloadPack } from '../hooks/useDownloadPack';
import { useOnlineStatus } from '../hooks/useOnlineStatus';
import { usePlatformCaptions } from '../hooks/usePlatformCaptions';
import { PLATFORMS } from '../types/platform';
import type { PlatformKey } from '../types/platform';
import CaptionCard from '../components/campaign/CaptionCard';
import PlatformPack from '../components/campaign/PlatformPack';
import SocialPreview from '../components/campaign/SocialPreview';
import QRCodeCard from '../components/campaign/QRCodeCard';
import KennelCard from '../components/campaign/KennelCard';
import ErrorBanner from '../components/ui/ErrorBanner';
import EmptyState from '../components/ui/EmptyState';
import Toast from '../components/ui/Toast';

const PAW_ICON = (
  <svg width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.25 }}>
    <ellipse cx="6.5" cy="5" rx="2" ry="2.5" />
    <ellipse cx="17.5" cy="5" rx="2" ry="2.5" />
    <ellipse cx="3.5" cy="11" rx="1.8" ry="2.2" />
    <ellipse cx="20.5" cy="11" rx="1.8" ry="2.2" />
    <ellipse cx="12" cy="15.5" rx="4.5" ry="4" />
  </svg>
);

export default function DownloadPage() {
  const { id } = useParams<{ id: string }>();
  const { pet, loading, error, isNotFound, refresh } = usePet(id);
  const { captions: platformCaptions, loading: captionsLoading, error: captionsError, generate: generateCaptions } = usePlatformCaptions(pet);
  const { downloadPlatform, downloadAll, progress, isGenerating, error: downloadError, skippedCount } = useDownloadPack(pet, platformCaptions);
  const [previewPlatform, setPreviewPlatform] = useState<PlatformKey | null>(null);
  const online = useOnlineStatus();
  const [showToast, setShowToast] = useState(false);
  const handleToastDone = useCallback(() => setShowToast(false), []);
  const autoGenerated = useRef(false);

  // Auto-generate platform captions when the page loads
  useEffect(() => {
    if (pet && !platformCaptions && !captionsLoading && !autoGenerated.current) {
      autoGenerated.current = true;
      generateCaptions();
    }
  }, [pet, platformCaptions, captionsLoading, generateCaptions]);

  async function handleCopyPlatformCaption(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      setShowToast(true);
    } catch {
      /* clipboard not available */
    }
  }

  /* ── Loading skeleton ──────────────────────── */
  if (loading) {
    return (
      <div className="page download-page">
        <div className="page-header">
          <div className="skeleton-line skeleton-line--title" style={{ width: '50%', marginBottom: '0.75rem' }} />
          <div className="skeleton-line" style={{ width: '35%' }} />
        </div>
        <div className="skeleton-card" style={{ padding: '2rem', marginBottom: '2rem' }}>
          <div className="skeleton-line" style={{ width: '90%', marginBottom: '0.5rem' }} />
          <div className="skeleton-line" style={{ width: '70%' }} />
        </div>
        <div className="download-grid">
          {[1, 2, 3, 4, 5].map((i) => (
            <div key={i} className="skeleton-card" style={{ height: 280 }} />
          ))}
        </div>
      </div>
    );
  }

  /* ── 404 not found ──────────────────────────── */
  if (isNotFound) {
    return (
      <div className="page download-page">
        <EmptyState
          icon={PAW_ICON}
          title="Pet not found"
          description="This pet may have been removed or the link is incorrect."
          action={{ label: 'Back to Gallery', to: '/gallery' }}
        />
      </div>
    );
  }

  /* ── Network/other error ────────────────────── */
  if (error || !pet) {
    return (
      <div className="page download-page">
        <ErrorBanner
          message={error || 'Something went wrong. Please try again.'}
          onRetry={refresh}
        />
        <div style={{ textAlign: 'center', marginTop: '1.5rem' }}>
          <Link to="/gallery" className="btn btn-outline">Back to Gallery</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="page download-page">
      {/* Header */}
      <div className="page-header">
        <h1>{pet.name} &mdash; Campaign Pack</h1>
        <p>Platform-optimized images and captions, ready to share.</p>
      </div>

      {/* Download error */}
      {downloadError && (
        <div style={{ marginBottom: '1.5rem' }}>
          <ErrorBanner message={downloadError} />
        </div>
      )}

      {/* Skipped images warning */}
      {skippedCount > 0 && !downloadError && (
        <div style={{ marginBottom: '1.5rem' }}>
          <ErrorBanner
            message={`${skippedCount} image${skippedCount > 1 ? 's' : ''} couldn't be downloaded and ${skippedCount > 1 ? 'were' : 'was'} skipped.`}
          />
        </div>
      )}

      {/* Progress bar */}
      {isGenerating && (
        <div className="progress-bar-wrapper">
          <div className="progress-bar">
            <div className="progress-bar-fill" style={{ width: `${progress}%` }} />
          </div>
          <span className="progress-bar-label">Generating ZIP &mdash; {progress}%</span>
        </div>
      )}

      {/* Caption card */}
      <CaptionCard caption={pet.caption} petName={pet.name} />

      {/* Platform-specific captions */}
      <div className="platform-captions-section">
        <div className="platform-captions-header">
          <h2 className="pet-section-title">Platform Captions</h2>
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={generateCaptions}
            disabled={captionsLoading || !online}
          >
            {captionsLoading ? (
              <span className="upload-spinner">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="spin">
                  <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                </svg>
                Generating...
              </span>
            ) : platformCaptions ? 'Regenerate Captions' : (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 3l1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3z" />
                </svg>
                Generate Platform Captions
              </>
            )}
          </button>
        </div>

        {captionsError && (
          <div style={{ marginTop: '0.75rem' }}>
            <ErrorBanner message={captionsError} onRetry={generateCaptions} />
          </div>
        )}

        {!platformCaptions && !captionsLoading && !captionsError && (
          <p className="platform-captions-hint">
            AI-powered captions tailored to each social media platform are being prepared...
          </p>
        )}

        {platformCaptions && (
          <div className="platform-captions-grid">
            {PLATFORMS.map((p) => {
              const pc = platformCaptions[p.key];
              if (!pc) return null;
              const hashtagsStr = pc.hashtags.length > 0 ? pc.hashtags.map((h) => `#${h}`).join(' ') : '';
              const fullText = pc.caption + (hashtagsStr ? '\n\n' + hashtagsStr : '');
              return (
                <div key={p.key} className="platform-caption-card">
                  <div className="platform-caption-card-header">
                    <span className="platform-caption-card-label">{p.label}</span>
                    <button
                      type="button"
                      className="btn btn-outline btn-sm"
                      onClick={() => handleCopyPlatformCaption(fullText)}
                      aria-label={`Copy ${p.label} caption`}
                    >
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                        <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                      </svg>
                      Copy
                    </button>
                  </div>
                  <div className="platform-caption-card-body">
                    <p className="platform-caption-card-text">{pc.caption}</p>
                    {hashtagsStr && (
                      <p className="platform-caption-card-hashtags">{hashtagsStr}</p>
                    )}
                  </div>
                  <span className="platform-caption-card-count">{fullText.length} characters</span>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Platform grid */}
      <h2 className="pet-section-title" style={{ marginTop: '2.5rem' }}>Platform Packs</h2>
      <div className="download-grid">
        {PLATFORMS.map((platform) => (
          <PlatformPack
            key={platform.key}
            pet={pet}
            platform={platform}
            onDownload={() => downloadPlatform(platform.key)}
            isGenerating={isGenerating || !online}
          />
        ))}
      </div>

      {/* Social preview */}
      <div className="social-preview-section">
        <h2 className="pet-section-title">Post Preview</h2>
        <div className="social-preview-tabs">
          {PLATFORMS.map((p) => (
            <button
              key={p.key}
              type="button"
              className={`social-preview-tab ${previewPlatform === p.key ? 'social-preview-tab--active' : ''}`}
              onClick={() => setPreviewPlatform(previewPlatform === p.key ? null : p.key)}
            >
              {p.label}
            </button>
          ))}
        </div>
        {previewPlatform && <SocialPreview pet={pet} platform={previewPlatform} />}
      </div>

      {/* QR Code + Kennel Card */}
      <div className="download-extras">
        <div className="download-extras-col">
          <h2 className="pet-section-title">QR Code</h2>
          <QRCodeCard petId={pet.id} petName={pet.name} />
        </div>
        <div className="download-extras-col">
          <h2 className="pet-section-title">Kennel Card</h2>
          <KennelCard pet={pet} />
        </div>
      </div>

      {/* Download all + back link */}
      <div className="download-actions">
        <button
          type="button"
          className="btn btn-primary btn-lg"
          onClick={downloadAll}
          disabled={isGenerating || !online}
        >
          {isGenerating ? (
            <span className="upload-spinner">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="spin">
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
              Generating...
            </span>
          ) : (
            <>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download All Platforms
            </>
          )}
        </button>
        <Link to={`/pet/${pet.id}`} className="btn btn-outline">
          Back to Profile
        </Link>
      </div>

      <Toast message="Caption copied!" visible={showToast} onDone={handleToastDone} />
    </div>
  );
}
